module.exports = {
		sex:[	{"value":"male","text":" Male"},
		 			{"value":"female","text":" Female"},
		 			{"value":"other","text":" Other"}
		 ],
		shirtsize:[
					{"value":"xs","text":" XS"},
		 			{"value":"s","text":" S"},
		 			{"value":"m","text":" M"},
		 			{"value":"l","text":" L"},
		 			{"value":"xl","text":" XL"},
					{"value":"xxl","text":" XXL"}

		],
		dietary:[
					{"value":"no","text":" No special restricitons"},
		 			{"value":"veg","text":" Vegan"},
		 			{"value":"glut","text":" Gluten free"},
		 			{"value":"pork","text":" No pork"},
		 			{"value":"other", "text":" Other - Please, describe in the free comments."}
		],
		track:[
					{"value":"gaming","text":" Gaming"},
		 			{"value":"vr","text":" Virtual Reality"},
		 			{"value":"iot","text":" IoT"},
		 			{"value":"dataDriven", "text":" Data Driven Economy"},
		 			{"value":"fintech", "text":" Fintech"},
		 			{"value":"ai", "text":" Artificial Intelligence"},
		 			{"value":"healthtech", "text":" Healthtech"},
					{"value":"buildings", "text":" Intelligent Buildings"},
					{"value":"ecommerce", "text":" E-Commerce"},
					{"value":"mobility", "text":" Future Mobility"},					

		],
			
		role:[		{"value":"software","text":" Software Dev"},
		 			{"value":"hardware","text":" Hardware Dev"},
		 			{"value":"designer","text":" Designer"},
		 			{"value":"business","text":" Business"},
		 			{"value":"other","text":" Other"},
		],
		
		occupation: [
			{"value":"Student","text":" Student - full-time"},
			{"value":"Full-Stack Web Developer","text":" Full-Stack Web Developer"},
			{"value":"Backend Web Developer","text":" Backend Web Developer"},
			{"value":"Frontend Web Developer","text":" Frontend Web Developer"},			
			{"value":"Mobile Developer","text":" Mobile Developer"},			
			{"value":"Manager / Executive","text":" Manager / Executive"},						
			{"value":"Data Scientist","text":" Data Scientist"},
			{"value":"Entrepreneur","text":" Entrepreneur"},
			{"value":"Analyst","text":" Analyst"},
			{"value":"Machine Learning Developer","text":" Machine Learning Developer"},
			{"value": 'UX Designer', text: ' UX Designer' },
			{"value":"Industrial Design","text":" Industrial Design"},
			{"value":"Web Design","text":" Web Design"},
			{"value":"Product Design","text":" Product Design"},
			{"value":"Other design related","text":" Other design related"},
			{"value":"Server Specialist","text":" Server Specialist"},
			{"value":"Hardware Technician","text":" Hardware Technician"},						
			{"value":"Hardware Engineer","text":" Hardware Engineer"},
			{"value": 'Game Designer', text: ' Game Designer' },
			{"value": 'Audio Design', text: ' Audio Design' },
			{"value": 'Artist', text: ' Artist' },
			{"value": 'Game Developer', text: ' Game Developer' },
			{"value": 'Graphic Designer', text: ' Graphic Designer' },
			{"value": "Unemployed","text":" Unemployed"},		
		],
		skills: [ {"value": 'Assembly language', text: ' Assembly language' },
				  {"value": 'Java', text: ' Java' },
				  {"value": 'C', text: ' C' },
				  {"value": 'C++', text: ' C++' },
				  {"value": 'C#', text: ' C#' },
				  {"value": 'Objective-C', text: ' Objective-C' },
				  {"value": 'PHP', text: ' PHP' },
				  {"value": 'Python', text: ' Python' },
				  {"value": 'Ruby', text: ' Ruby' },
				  {"value": 'JavaScript', text: ' JavaScript' },
				  {"value": 'SQL', text: ' SQL' },
				  {"value": 'Perl', text: ' Perl' },
				  {"value": 'HTML', text: ' HTML' },
				  {"value": 'CSS', text: ' CSS' },
				  {"value": 'Swift', text: ' Swift' },
				  {"value": 'Scala', text: ' Scala' },
				  {"value": 'Unity', text: ' Unity' },
				  { "value": 'Unreal Engine', text: ' Unreal Engine' },
				  { "value": 'Construct 2', text: ' Construct 2' },
				  { "value": 'GameMaker', text: ' GameMaker' },
				  { "value": 'HTML5', text: ' HTML5'},				  
				  {"value": 'Go', text: ' Go' },
				  {"value": 'R', text: ' R' },
				  {"value": 'Matlab', text: ' Matlab' },
				  {"value": 'Haskell', text: ' Haskell' },
				  {"value": 'Clojure', text: ' Clojure' },
				  {"value": 'Bash', text: ' Bash' },
				  {"value": 'Other', text: ' Other' },
				  {"value": 'PowerPoint', text: ' PowerPoint' },
				  {"value": 'Excel', text: ' Excel' },
				  {"value": 'None of the above', text: ' None of the above' },
				
				   ],

		operating: [ {"value": 'Mac OS X (all versions)', text: ' Mac OS X (all versions)' },
				  {"value": 'Windows 10', text: ' Windows 10' },
				  {"value": 'Windows 8.1', text: ' Windows 8.1' },
				  {"value": 'Windows 7', text: ' Windows 7' },
				  {"value": 'Windows: Some other', text: ' Windows: Some other' },
				  {"value": 'Ubuntu', text: ' Ubuntu' },
				  {"value": 'Fedora', text: ' Fedora' },
				  {"value": 'Mint', text: ' Mint' },
				  {"value": 'Debian', text: ' Debian' },
				  {"value": 'Chrome OS', text: ' Chrome OS' },
				  {"value": 'Some other Linux kernel based', text: ' Some other Linux kernel based' },
				  {"value": 'Other', text: ' Other' },
				  {"value": 'I’m not bringing my laptop', text: ' I’m not bringing my laptop' } ],


			role: [ 
			{"value": 'Frontend Developer', text: ' Frontend Developer' },
				  {"value": 'Backend Developer', text: ' Backend Developer' },
				  {"value": 'Full-Stack Developer', text: ' Full-Stack Developer' },
				  {"value": 'Designer', text: ' Designer' },
				  {"value": 'Game Designer', text: ' Game Designer'},
				  {"value": 'Audio Design', text: ' Audio Design'},
				  {"value": 'Artist', text: ' Artist' },
				  {"value": 'Game Developer', text: ' Game Developer' },
				  {"value": 'Graphic Designer', text: ' Graphic Designer' },				  
				  {"value": 'Ideation', text: ' Ideation' },
				  {"value": 'Business Development', text: ' Business Development' },
				  {"value": 'Product Development', text: ' Product Development' },				  
				  {"value": 'Marketing', text: ' Marketing' },
				  {"value": 'Hardware', text: ' Hardware' },				  
				  {"value": 'Buzzing around', text: ' Buzzing around' },
				  {"value": 'Moral support', text: ' Moral support' },
				  {"value": 'I do everything', text: ' I do everything' },
				  {"value": 'I work without a team', text: ' I work without a team' },
				  {"value": 'Something else', text: ' Something else' } ],

			experience: [ {"value": 'None', text: ' None' },
						  {"value": '< 1 Year', text: ' < 1 Year' },
						  {"value": '1-2 Years', text: ' 1-2 Years' },
						  {"value": '3-5 Years', text: ' 3-5 Years' },
						  {"value": '5+ Years', text: ' 5+ Years' } ],

			tc: [{"value": "agree", text: ' I agree'}],

			sublime: [{"value": "Yes", text: ' Yes'}, {"value": "No", text: ' No'}]
	
}